name: Deploy Connect Cluster

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['2.x', '3.x']
        
    steps:
    - uses: actions/checkout@v2

    - name: Install Python
      run: |
        sudo subscription-manager repos --enable rhel-7-server-optional-rpms --enable rhel-server-rhscl-7-rpms
        sudo yum -y install @development
        sudo yum -y install rh-python36
        sudo yum -y install rh-python36-numpy rh-python36-scipy rh-python36-python-tools rh-python36-python-six
        
    - name: Install Ansible
      run: |
        sudo apt update
        sudo apt install -y ansible
        ansible-galaxy collection install git+https://github.com/confluentinc/cp-ansible.git,7.3.2-post


    - name: Install jinja2 and libyaml
      run: |
        pip install jinja2==3.1.2 PyYAML

    - name: Generate hosts file
      env:
        HOSTS_DEV_FILE: "hosts-dev.yml" # Modify this line to select the desired file
        ANSIBLE_HASH_BEHAVIOUR: merge
        CCLOUD_KEY: ${{ secrets.CCLOUD_KAFKA_KEY }}
        CCLOUD_SECRET: ${{ secrets.CCLOUD_KAFKA_SECRET }}
      run: |
        python generate_hosts.py -i ${{ env.HOSTS_DEV_FILE }} -t inventory.j2 -o hosts.yml

    - name: Deploy Connect cluster
      run: |
        ansible-playbook -i hosts.yml confluent.platform.all --tags=kafka_connect

