name: Deploy Connect Cluster

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: [self-hosted,aws-rhel7]

    steps:
    - uses: actions/checkout@v3

    - name: Install Python
      run: |
          sudo yum install python3
          sudo yum -y install numpy
          sudo yum -y install scipy
          python3 -m pip install --upgrade pip
    - name: Check Python version
      run: python3 --version

    - name: Install Ansible
      run: python3 -m pip install ansible-core==2.11.12

    - name: Install Confluent collection
      run: |
          ansible-galaxy collection install git+https://github.com/confluentinc/cp-ansible.git,7.3.2-post
          ansible-galaxy collection install ansible.posix

    - name: Check Ansible version
      run: ansible --version

    - name: Create SSH directory
      run: mkdir -p ~/.ssh

    - name: Copy SSH key
      run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa_ansible.pem
          chmod 600 ~/.ssh/id_rsa_ansible.pem

    - name: Generate hosts file
      env:
        HOSTS_DEV_FILE: "hosts-dev.yml" # Modify this line to select the desired file
        ANSIBLE_HASH_BEHAVIOUR: merge
        CCLOUD_KEY: ${{ secrets.CCLOUD_KAFKA_KEY }}
        CCLOUD_SECRET: ${{ secrets.CCLOUD_KAFKA_SECRET }}
      run: |
        python generate_hosts.py -i ${{ env.HOSTS_DEV_FILE }} -t inventory.j2 -o hosts.yml
    - name: Deploy Connect cluster
      run: |
        ansible-playbook -i hosts.yml confluent.platform.all --tags=kafka_connect
