all:
  vars:
    ansible_connection: ssh
    ansible_user: ubuntu
    ansible_become: true
    ansible_ssh_private_key_file: /Users/rsoltani/Downloads/keys/ramzi-ec2.pem

    ccloud_kafka_enabled: true
    ccloud_kafka_bootstrap_servers: pkc-xxx.us-west-2.aws.confluent.cloud:9092
    ccloud_kafka_key: ${{ secrets.SECRET_NAME }}
    ccloud_kafka_secret: bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb

    ccloud_schema_registry_enabled: true
    ccloud_schema_registry_url: 
    ccloud_schema_registry_key: 
    ccloud_schema_registry_secret: 

    kafka_connect_cluster_name: takeda-connect
    kafka_connect_service_overrides:
      ExecStartPost: /bin/bash -c "sleep 10;jps -lm | awk '/ConnectDistributed/ {print $1}' > /etc/kafka/kafka.pid"
    kafka_connect_custom_java_args: "-javaagent:/opt/appdynamics/appagent/ver22.4.0.33722/javaagent.jar -Dappdynamics.agent.uniqueHostId=93255-usvgackcd003"

kafka_connect:
  vars:
    kafka_connect_confluent_hub_plugins:
      - confluentinc/kafka-connect-jdbc:10.6.4
      
  hosts:
    
    ip-172-30-47-87.us-west-2.compute.internal:
    
    ip-172-30-33-233.us-west-2.compute.internal:
    

#  control_center:
#    hosts:
#      