name: Terraform Create Service Account

on:
  push:
    branches:
      - main

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Terraform Init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: <your-S3-bucket-region>
        working-directory: takeda-terraform/kafka-sa
        run: |
          terraform init \
            -backend-config="bucket=<your-S3-bucket-name>" \
            -backend-config="key=<your-S3-bucket-key>" \
            -backend-config="region=<your-S3-bucket-region>"
      - name: Terraform Apply
        env:
          CONFLUENT_CLOUD_API_KEY: ${{ secrets.CONFLUENT_CLOUD_API_KEY }}
          CONFLUENT_CLOUD_API_SECRET: ${{ secrets.CONFLUENT_CLOUD_API_SECRET }}
          KAFKA_ID: ${{ secrets.KAFKA_ID }}
          KAFKA_REST_ENDPOINT: ${{ secrets.KAFKA_REST_ENDPOINT }}
          KAFKA_API_KEY: ${{ secrets.KAFKA_API_KEY }}
          KAFKA_API_SECRET: ${{ secrets.KAFKA_API_SECRET }}
        working-directory: takeda-terraform/kafka-sa
        run: terraform apply -auto-approve
      - name: Terraform Show
        working-directory: takeda-terraform/kafka-sa
        run: terraform show
